#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

[[ -f ~/.welcome_screen ]] && . ~/.welcome_screen

alias ls='ls --color=auto'
alias ll='ls -lav --ignore=..'   # show long listing of all except ".."
alias l='ls -lav --ignore=.?*'   # show long listing but no hidden dotfiles except "."

# PS1='[\u@\h \W]\$ '

## Use up and down arrow keys for finding a command in history
## (after writing some letters first).
bind '"\e[A":history-search-backward'
bind '"\e[B":history-search-forward'

################################################################################
## Some generally useful functions.
## Consider uncommenting aliases below to start using these functions.

_open_files_for_editing() {
    # Open any given document file(s) for editing (or just viewing).
    # Note1: Do not use for executable files!
    # Note2: uses mime bindings, so you may need to use
    #        e.g. a file manager to make some file bindings.

    local progs="xdg-open exo-open"     # One of these programs is used.
    local prog
    for prog in $progs ; do
        if [ -x /usr/bin/$xx ] ; then
            $prog "$@" >& /dev/null &
            return
        fi
    done
    echo "Sorry, none of programs [$progs] is found." >&2
}
#------------------------------------------------------------

## Aliases for the functions above.
## Uncomment an alias if you want to use it.
##
# alias ef='_open_files_for_editing'     # 'ef' opens given file(s) for editing
################################################################################

# PS1="\[\e[38;5;43m\]bee\[\e[38;5;157m\]@\[\e[38;5;215m\]hive\[\e[0m\] \[\e[38;5;39m\]\W \[\e[0m\]$ "
PS1="\[\e[38;5;228m\]bee\[\e[38;5;220m\]@\[\e[38;5;215m\]hive\[\e[0m\] \[\e[38;5;39m\]\W \[\e[0m\]$ "
LS_COLORS=$LS_COLORS:'*.pdf=38;5;227' ; export LS_COLORS
LS_COLORS=$LS_COLORS:'*.fastq=38;5;156' ; export LS_COLORS
LS_COLORS=$LS_COLORS:'*.fasta=38;5;121' ; export LS_COLORS
LS_COLORS=$LS_COLORS:'*.py=38;5;43:' ; export LS_COLORS
LS_COLORS=$LS_COLORS'*.cu=38;5;76:' ; export LS_COLORS
LS_COLORS=$LS_COLORS'*.go=38;5;38:' ; export LS_COLORS
LS_COLORS=$LS_COLORS'*.c=38;5;74:' ; export LS_COLORS
LS_COLORS=$LS_COLORS'*.png=38;5;221:' ; export LS_COLORS
LS_COLORS=$LS_COLORS'*.jpg=38;5;221:' ; export LS_COLORS
LS_COLORS=$LS_COLORS'*.jpeg=38;5;221:' ; export LS_COLORS
LS_COLORS=$LS_COLORS'*.svg=38;5;98:' ; export LS_COLORS
alias open='xdg-open'
alias k2so='ssh -CY vulpter@128.114.151.165'
alias ig88='ssh -CY ig88@128.114.151.147'
alias sudo='sudo '
alias pbcopy="xclip -sel clip"
alias cpwd="pwd | tr -d '\n' | pbcopy && echo 'pwd copied to clipboard'"
alias controller='sudo chmod 777 /dev/input/*'
alias le='less -S'
alias updoot='yay -Syyu'
alias battery='sudo tlp start && sudo powertop --auto-tune'
alias pdf='evince'
alias cups='sudo systemctl start org.cups.cupsd.service'
alias fanOff='i8kctl fan 0 0'
alias fanLo='i8kctl fan 1 1'
alias fanHi='i8kctl fan 2 2'
alias nmclilist='nmcli dev wifi'
alias nmcliconnect='nmcli dev wifi con'
