syntax enable
set nowrap
set number
set background=dark
set ruler
set smarttab
set tabstop=4
set softtabstop=4
set autoindent
set smartindent
set expandtab
set smartcase
set wildmenu
set ignorecase
set hlsearch
set shiftwidth=4
set background=dark
if (has("termguicolors"))
  set termguicolors
endif
colorscheme OceanicNext
let g:oceanic_next_terminal_bold = 1
let g:oceanic_next_terminal_italic = 1
"colorscheme hybrid_material
filetype plugin indent on

set noshowmode

set encoding=utf8
call plug#begin('~/.vim/plugged')

Plug 'ervandew/supertab'
Plug 'mengelbrecht/lightline-bufferline'
Plug 'itchyny/lightline.vim'
Plug 'tmhedberg/SimpylFold'
Plug 'ryanoasis/vim-devicons'
Plug 'airblade/vim-gitgutter'
Plug 'thaerkh/vim-indentguides'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
Plug 'kshenoy/vim-signature'
Plug 'easymotion/vim-easymotion'
Plug 'jiangmiao/auto-pairs'
Plug 'vim-python/python-syntax'

call plug#end()

set updatetime=100
set listchars=""
let g:indentguides_tabchar = '|'
let g:indentguides_spacechar = '|'

let g:lightline = {
    \ 'colorscheme': 'one',
    \ }

map fd :bn<cr>
map df :bp<cr>

let g:lightline.tabline          = {'left': [['buffers']], 'right': [['close']]}
let g:lightline.component_expand = {'buffers': 'lightline#bufferline#buffers'}
let g:lightline.component_type   = {'buffers': 'tabsel'}
set showtabline=2
set laststatus=2
let g:lightline#bufferline#shorten_path = 1

let g:SimpylFold_docstring_preview = 1
let g:SimpylFold_fold_docstring = 0
let g:SimpylFold_fold_import = 0
set fdls=99

let g:EasyMotion_do_mapping = 0 " Disable default mappings

" Jump to anywhere you want with minimal keystrokes, with just one key binding.
" `s{char}{label}`
nmap s <Plug>(easymotion-overwin-f)
" or
" `s{char}{char}{label}`
" Need one more keystroke, but on average, it may be more comfortable.
" nmap s <Plug>(easymotion-overwin-f2)

" Turn on case-insensitive feature
let g:EasyMotion_smartcase = 1

" JK motions: Line motions
map <Leader>k <Plug>(easymotion-j)
map <Leader>j <Plug>(easymotion-k)
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"

let g:python_version_2 = 0
let g:python_highlight_all = 1
